# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Troupeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boucle_ovin', models.CharField(help_text="Identifiant de l'animal (réutilisable quand inactif)", max_length=20, verbose_name='Numéro de boucle')),
                ('sexe', models.CharField(choices=[('male', 'Mâle'), ('femelle', 'Femelle')], max_length=10, verbose_name='Sexe')),
                ('race', models.CharField(choices=[('bali_bali', 'BALI-BALI'), ('balami', 'BALAMI'), ('oudah', 'OUDAH'), ('ladoun', 'LADOUN'), ('koundoum', 'KOUNDOUM'), ('macina', 'MACINA')], max_length=50, verbose_name='Race')),
                ('naissance_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('boucle_active', models.BooleanField(default=True, help_text="Indique si l'animal est encore dans le troupeau", verbose_name='Boucle active')),
                ('poids_initial', models.FloatField(blank=True, help_text="Poids à l'entrée ou à la naissance", null=True, verbose_name='Poids initial (kg)')),
                ('taille_initiale', models.FloatField(blank=True, help_text='Hauteur au garrot', null=True, verbose_name='Taille initiale (cm)')),
                ('achat_date', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('entree_date', models.DateField(blank=True, help_text="Date d'arrivée dans la ferme", null=True, verbose_name="Date d'entrée")),
                ('date_sortie', models.DateField(blank=True, null=True, verbose_name='Date de sortie')),
                ('statut', models.CharField(choices=[('naissance', 'Naissance'), ('vendu', 'Vendu'), ('decede', 'Décédé'), ('sortie', 'Sortie'), ('pret_notre_ferme', 'Prêt notre ferme'), ('pret_autre_ferme', 'Prêt autre ferme'), ('echange_ovin', 'Échange Ovin'), ('achat', 'Achat')], max_length=30, verbose_name='Statut')),
                ('origine_ovin', models.CharField(choices=[('cotonou', 'Cotonou'), ('porto_novo', 'Porto-Novo'), ('abomey_calavi', 'Abomey-Calavi'), ('ouidah', 'Ouidah'), ('seme_kpodji', 'Sèmè-Kpodji'), ('akpakpa', 'Akpakpa'), ('godomey', 'Godomey'), ('tori_bossito', 'Tori-Bossito'), ('pahou', 'Pahou'), ('avrankou', 'Avrankou'), ('ifangni', 'Ifangni'), ('ketou', 'Kétou'), ('come', 'Comè'), ('lokossa', 'Lokossa'), ('dassa_zoume', 'Dassa-Zoumé')], max_length=50, verbose_name='Origine')),
                ('proprietaire_ovin', models.CharField(choices=[('miguel', 'Miguel'), ('famille', 'Famille')], max_length=50, verbose_name='Propriétaire')),
                ('observations', models.TextField(blank=True, help_text="Notes diverses sur l'animal", null=True, verbose_name='Observations')),
                ('coefficient_consanguinite', models.FloatField(default=0.0, help_text='Calculé automatiquement selon Wright', verbose_name='Coefficient de consanguinité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mere_boucle', models.ForeignKey(blank=True, limit_choices_to={'boucle_active': True, 'sexe': 'femelle'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agneaux_mere', to='troupeau.troupeau', verbose_name='Mère')),
                ('pere_boucle', models.ForeignKey(blank=True, limit_choices_to={'boucle_active': True, 'sexe': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agneaux_pere', to='troupeau.troupeau', verbose_name='Père')),
            ],
            options={
                'verbose_name': 'Animal du troupeau',
                'verbose_name_plural': 'Animaux du troupeau',
                'db_table': 'troupeau',
                'ordering': ['-naissance_date'],
                'indexes': [models.Index(fields=['boucle_ovin'], name='troupeau_boucle__98624e_idx'), models.Index(fields=['sexe'], name='troupeau_sexe_ad0dc9_idx'), models.Index(fields=['race'], name='troupeau_race_259365_idx'), models.Index(fields=['statut'], name='troupeau_statut_7d43fd_idx'), models.Index(fields=['boucle_active'], name='troupeau_boucle__7a8ee2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('boucle_active', True)), fields=('boucle_ovin',), name='uniq_boucle_ovin_active')],
            },
        ),
    ]
