# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embouche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField(verbose_name="Date d'entrée")),
                ('poids_initial', models.FloatField(verbose_name='Poids initial (kg)')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('poids_fin', models.FloatField(blank=True, null=True, verbose_name='Poids final (kg)')),
                ('duree', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (jours)')),
                ('poids_engraissement', models.FloatField(blank=True, null=True, verbose_name="Poids d'engraissement (kg)")),
                ('proprietaire', models.CharField(choices=[('miguel', 'Miguel'), ('famille', 'Famille')], max_length=20, verbose_name='Propriétaire')),
                ('sexe', models.CharField(choices=[('male', 'Mâle'), ('femelle', 'Femelle')], max_length=10, verbose_name='Sexe')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('boucle_ovin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embouches', to='troupeau.troupeau', verbose_name='Boucle ovin')),
            ],
            options={
                'verbose_name': 'Embouche',
                'verbose_name_plural': 'Embouches',
                'ordering': ['-date_entree', '-id'],
                'indexes': [models.Index(fields=['boucle_ovin'], name='embouche_em_boucle__b134ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('boucle_ovin', 'date_entree'), name='unique_boucle_date')],
            },
        ),
    ]
