# Generated by Django 5.2.4 on 2026-01-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embouche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embouche',
            name='proprietaire',
            field=models.CharField(choices=[('miguel', 'Miguel'), ('virgile', 'Virgile')], max_length=20, verbose_name='Propriétaire'),
        ),
    ]
