# Generated by Django 5.2.4 on 2025-08-23 07:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troupeau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateField(verbose_name='Date de vente')),
                ('poids_kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Poids (kg)')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix de vente')),
                ('type_acheteur', models.CharField(choices=[('Elevage', 'Elevage'), ('Abattage', 'Abattage'), ('Reproduction', 'Reproduction')], max_length=20, verbose_name='Type d’acheteur')),
                ('proprietaire_ovin', models.CharField(choices=[('Famille', 'Famille'), ('Miguel', 'Miguel')], max_length=20, verbose_name='Propriétaire')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('boucle_ovin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='troupeau.troupeau', verbose_name='Ovin')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
                'indexes': [models.Index(fields=['date_vente'], name='vente_vente_date_ve_588cc6_idx'), models.Index(fields=['type_acheteur'], name='vente_vente_type_ac_6f1c92_idx'), models.Index(fields=['proprietaire_ovin'], name='vente_vente_proprie_22539a_idx'), models.Index(fields=['boucle_ovin'], name='vente_vente_boucle__fc5d83_idx')],
                'constraints': [models.UniqueConstraint(fields=('boucle_ovin', 'date_vente'), name='uniq_vente_ovin_date')],
            },
        ),
    ]
